import Head from "next/head";
import dynamic from "next/dynamic";



import "swiper/css";

const VideoSliderHero = dynamic(() => import("components/VideoSliderHero"), {
  ssr: false,
})

import Welcome from "components/welcome";
import Concept from "components/Concept";
import Slide from "components/Slide";
import Reviews from "components/Reviews";
import Experience from "components/Experience";
import NextUp from "components/NextUp";
import { FaWhatsapp } from "react-icons/fa";




export default function Home() {
 
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main className="mt-20">
        <VideoSliderHero />
        <Welcome />
        <Concept />
        <Slide />
        <Reviews />
        <Experience />
        <NextUp />
        <div className="fixed  z-30 flex sm:hidden justify-end p-8  bottom-0 w-full h-auto">
           
           <a  href="https://wa.me/+6281353669377" target="_target">
  
            <FaWhatsapp className=" fill-purple" size={40} />
           </a>

         
          </div>
      </main>
    </>
  );
}
